### ISSUE TITLE
Automatic "mail_engine" dropdown values in Settings.php Action

### ISSUE THREAD

**Issue by jeroendesloovere** [mailmotor/fork-cms-module-mailmotor#3]
**What I want**
* Automatic dropdown values for the "mail_engine".
* Based on the bundles that are activated.
* So when somebody activates a new "mail-motor" supported bundle, they automatically can select it.

**Comment by WouterSioen** [comment]
The Symfony Finder component could maybe help for this?

**Comment by jeroendesloovere** [comment]
I thought about getting all serviceIds() and then looking for "mailmotor.*.gateway".

**Comment by WouterSioen** [comment]
hmm, this could even be a better option, since this won't require filesystem actions.

**Comment by jeroendesloovere** [comment]
Fixed by https://github.com/mailmotor/fork-cms-module-mailmotor/commit/b323db61f39d93f5f068defe4825dba8c3c3f418
