### ISSUE TITLE
Translations not working very well

### ISSUE THREAD

**Issue by jessedobbelaere** [mailmotor/fork-cms-module-mailmotor#5]
Some translations don't work, like on the settings page for example, and in the left sidebar of the Settings/modules tab. 

We have a `{lblMailMotor}` in the template, and in the locale.xml there is a label with name MailMotor in the Core section, so that should work. **However**, it doesnt work and I think the locale gets ucfirst'ed somehow. When you change the locale.xml core label to `Mailmotor`, it works. 

Suggestion: Change the word MailMotor everywhere to Mailmotor. The module foldername, the modulename in the installer, etc. The old mailmotor module also did this. 

It also does this in the installer.php:

        // settings navigation
        $navigationSettingsId = $this->setNavigation(null, 'Settings');
        $navigationModulesId = $this->setNavigation($navigationSettingsId, 'Modules');
        $this->setNavigation($navigationModulesId, $this->getModule(), 'mail_motor/settings');

Where `$this->getModule()` would fetch `MailMotor`, but it has to be Mailmotor for the locale to work... Anyway, something like that could fix it.

**Comment by jeroendesloovere** [comment]
Thats probably because you had the previous "Mailmotor" installed and just overwrited the thing.
This wouldn't be a problem when de MailMotor is default.

**Comment by jessedobbelaere** [comment]
Hmm not really. Did a clean install, mailmotor is by default unchecked during installation. Then I removed the original mailmotor and added the new mailmotor module. Installed it. Got some translation problems. We'll see if other people have the same issue..

**Comment by jeroendesloovere** [comment]
I'll further check this out in the core locale.

**Comment by jeroendesloovere** [comment]
Yep, found it.

**Comment by jeroendesloovere** [comment]
Will be fixed in the core when I add my Pull Request for integrating the MailMotor
